GET http://localhost:8080/greeting

###
POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": {"x": 3, "y": -2},
  "second_pos": {"x": -1, "y": 1}
}

###
GET http://localhost:8080/robots